Thrift driver
PLVision/SAI-Challenger.OCP pull request #11
Opened 2022-09-11 22:16 UTC by elchupanebrej

2022-09-12 09:00 UTC, anton7811 requested changes

2022-09-12 09:00 UTC, anton7811 commented on docs/scale&configurability.md
> +Sai-Challenger allows setup huge sized configuration. These configuration are generated by external tool named **Generate SAI**.
Since saigen is not a part of SAI-Challenger. I would concentrate the doc on SAI-centric testing agnostic from southbound API.

2022-09-12 09:00 UTC, anton7811 commented on docs/scale&configurability.md
> +Configurations could be applied by different appliance APIs (SONiC Orchagent, SAI thrift, etc.).
Orchagent we cannot touch. We have the drivers for SAI-Thrift, Redis ASIC DB.

2022-09-12 09:04 UTC, anton7811 requested changes

2022-09-12 09:04 UTC, anton7811 commented on common/sai_client/sai_thrift_client/sai_thrift_client.py
> +                calculated_oid_id = self.thrift_client.sai_thrift_object_type_query(self.oid_to_int(oid))
I wonder how it will look like in scaled config. If we do query every time, it might be a performance issue.

2022-09-12 09:05 UTC, taniazplv commented on docs/scale&configurability.md
> +Also Sai-Challenger is a testing tool, so it provides meaningful test preconditions and setups
We position / present SAI-Challenger as a Framework, not a tool, not a mediator/ please correct

2022-09-12 09:06 UTC, taniazplv commented on docs/scale&configurability.md
> +<a href="url"><img src="../img/DASH test framework-DASH Syncer HL.drawio.svg" align="center" width="800" ></a>
We shall not mention DASH here.

2022-09-12 10:49 UTC, elchupanebrej commented on docs/scale&configurability.md
> +Sai-Challenger allows setup huge sized configuration. These configuration are generated by external tool named **Generate SAI**.
Please check new wording

2022-09-12 10:49 UTC, elchupanebrej commented on docs/scale&configurability.md
> +Configurations could be applied by different appliance APIs (SONiC Orchagent, SAI thrift, etc.).
Fixed, please check

2022-09-12 10:49 UTC, elchupanebrej commented on docs/scale&configurability.md
> +be setup using same commands using different API backends. Same for traffic generation/validation tools
Added section for config, please check

2022-09-12 10:50 UTC, elchupanebrej commented on docs/scale&configurability.md
> +Because of above schema Sai class don't have to know anything about low-API level and because of this appliance could
Add extra wording, please check

2022-09-12 10:50 UTC, elchupanebrej commented on unit_tests/test_command_processor.py
> +def test_command_processor():
Added, please check

2022-09-12 10:50 UTC, elchupanebrej commented on common/sai_object.py
>      PORT = _placeholder_init
Comment added. It's already generated, TODO is not needed

2022-09-12 10:51 UTC, elchupanebrej commented on docs/scale&configurability.md
> +## Objective
Added new doc section

2022-09-12 11:08 UTC, anton7811 requested changes

2022-09-12 11:08 UTC, anton7811 commented on common/sai_client/sai_thrift_client/sai_thrift_client.py
>      def get_object_type(self, oid, default=None) -> SaiObjType:
Since we can explicitly pass the type IMO it's better to name this attribute "obj_type" or "expected_obj_type"

2022-09-12 11:08 UTC, anton7811 commented on unit_tests/test_command_processor.py
> +def test_command_processor():
As I understand this is a unit test and it has some purpose. The same for all tests bellow.

2022-09-12 11:26 UTC, maksym-prytoliuk-plv commented on common/sai_client/sai_thrift_client/sai_thrift_client.py
> +                calculated_oid_id = self.thrift_client.sai_thrift_object_type_query(self.oid_to_int(oid))
It should not be a big deal. Generally, this function doesn't call SDK and must be very quick. But if RPC for this call will take longer then - yes, it might be a problem. I suggest we can make another function which will call sai_thrift_object_type_query in the meanwhile if we find any performance problems we will update this function only.

2022-09-12 11:26 UTC, maksym-prytoliuk-plv commented on common/sai_client/sai_client.py
> +        Remove SAI object by oid or by key
Should obj_type be provided if oid is provided?

2022-09-12 11:26 UTC, maksym-prytoliuk-plv commented on common/sai_client/sai_client.py
> +        """
Probably we need to cover all possible use cases for CRUD functions. Like if we hay key - there should be no oid. If there is oid we don't expect key, etc.

2022-09-12 11:54 UTC, elchupanebrej commented on common/sai_client/sai_thrift_client/sai_thrift_client.py
> +                calculated_oid_id = self.thrift_client.sai_thrift_object_type_query(self.oid_to_int(oid))
Fixed, now obj_type calculated from oid if default type wasn't provided

2022-09-12 11:54 UTC, elchupanebrej commented on docs/scale&configurability.md
> +Also Sai-Challenger is a testing tool, so it provides meaningful test preconditions and setups
Fixed wording. Please check

2022-09-12 11:54 UTC, elchupanebrej commented on docs/scale&configurability.md
> +<a href="url"><img src="../img/DASH test framework-DASH Syncer HL.drawio.svg" align="center" width="800" ></a>
Done

2022-09-12 11:55 UTC, elchupanebrej commented on docs/scale&configurability.md
> +* Appliance configuration per se
https://en.wiktionary.org/wiki/per_se

2022-09-12 11:59 UTC, elchupanebrej commented on common/sai_client/sai_client.py
> +        Remove SAI object by oid or by key
No, but there is no native Python instrument to make dispatching for function by argument names. I would like to save the function signature easy to read without extra complexity. I could implement such dispatching if  you insist

2022-09-12 12:00 UTC, elchupanebrej commented on common/sai_client/sai_client.py
> +        Remove SAI object by oid or by key
> Should obj_type be provided if oid 
If it provided - it will save RPC call

2022-09-26 11:52 UTC, anton7811 commented
All changes are merged as a part of PR #12

2022-09-26 11:52 UTC, closed without merging